In [1]:
from sklearn.datasets import load_iris

In [2]:
iris_data = load_iris()
print(iris_data)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [3]:
data_input = iris_data.data
data_output = iris_data.target

In [4]:
print(data_input)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
print(data_output)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [9]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 5, shuffle=True)

In [13]:
print("Train Set          Test Set        ")
for train_set,test_set in kf.split(data_input):
    print(train_set, test_set)

Train Set          Test Set        
[  1   3   4   7   8   9  10  11  12  13  15  16  17  18  20  21  23  24
  25  26  27  28  29  30  31  32  33  34  35  36  37  38  41  42  43  46
  48  49  51  52  53  54  55  56  57  58  61  62  63  65  66  68  69  70
  71  72  73  75  76  77  79  80  81  82  84  85  88  89  90  91  92  93
  94  95  96  97  98  99 101 102 104 105 106 107 108 109 110 111 112 113
 114 115 116 117 118 119 120 121 122 123 124 126 127 128 129 130 131 133
 134 135 136 139 140 142 143 145 146 147 148 149] [  0   2   5   6  14  19  22  39  40  44  45  47  50  59  60  64  67  74
  78  83  86  87 100 103 125 132 137 138 141 144]
[  0   1   2   4   5   6   8   9  10  12  13  14  17  18  19  22  24  26
  27  28  29  30  31  32  33  35  36  37  38  39  40  41  42  44  45  47
  48  49  50  52  54  55  57  58  59  60  61  63  64  65  66  67  68  69
  70  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88
  91  93  94  95  96  97  98  99 100 101 102 103 105 106 108 

In [14]:
kf = KFold(n_splits = 10, shuffle=True)
 
print("Train Set          Test Set        ")
 
for train_set,test_set in kf.split(data_output):
    print(train_set, test_set)

Train Set          Test Set        
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  24  25  26  27  28  30  31  32  33  34  36  37  38  39
  41  42  43  45  46  47  48  49  50  51  52  53  54  55  56  57  58  60
  61  62  63  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79
  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  96  98 100
 101 102 103 104 105 106 107 108 109 110 111 113 114 115 116 117 119 120
 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138
 139 140 141 142 145 146 147 148 149] [ 22  23  29  35  40  44  59  64  95  97  99 112 118 143 144]
[  0   1   2   3   4   5   6   7   8   9  10  12  13  14  15  16  18  19
  20  21  22  23  25  26  27  29  30  31  33  34  35  36  38  39  40  41
  42  43  44  45  46  47  48  49  50  51  52  54  55  57  58  59  61  62
  63  64  65  66  67  68  69  70  71  72  73  74  75  76  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  95  96  97  98 

In [16]:
from sklearn.ensemble import RandomForestClassifier
rf_class = RandomForestClassifier(n_estimators=10)

C:\Users\atul.singh.SSPL-LP-HP-0166\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [18]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(rf_class, data_input, data_output, scoring='accuracy', cv = 10))

[1.         0.93333333 1.         0.93333333 0.93333333 0.86666667
 0.86666667 1.         1.         1.        ]


In [19]:
accuracy = cross_val_score(rf_class, data_input, data_output, scoring='accuracy', cv = 10).mean() * 100
print("Accuracy of Random Forests is: " , accuracy)

Accuracy of Random Forests is:  95.33333333333334
